services:
  smaug_app:
    user: $DOCKER_USER:$DOCKER_GROUP
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: smaug_app
    volumes:
      - ./:/app
    ports:
      - "8010:8000"
    depends_on:
      - smaug_db
      - smaug_redis
    networks:
      - smaug
    environment:
      - AWS_PROFILE=staging
      - REDIS_HOST=smaug_redis

  smaug_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: smaug_db
    ports:
      - "33072:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smaug
    volumes:
      - smaug_db:/var/lib/mysql
    networks:
      - smaug

  smaug_redis:
    image: redis:7.0.2
    container_name: smaug_redis
    ports:
      - "63792:6379"
    volumes:
      - smaug_redis:/data
    networks:
      - smaug

networks:
  smaug:
    driver: bridge

volumes:
  smaug_db:
  smaug_redis: